static const char black[]     = "#0e0e0e";      // Negro puro
static const char white[]     = "#c0c0c0";     // Gris claro (casi blanco)
static const char gray2[]     = "#0e0e0e";     // Gris muy oscuro (borde ventana inactiva)
static const char gray3[]     = "#484847";     // Gris oscuro
static const char gray4[]     = "#0e0e0e";     // Gris muy claro
static const char red[]       = "#ff0000";     // Rojo puro (borde ventana activa)
static const char dark_red[]  = "#5e0e0e";     // Rojo oscuro (antes verde)
static const char red2[]      = "#ff3300";     // Rojo anaranjado
static const char brown_red[] = "#801a00";     // Rojo parduzco oscuro (antes naranja)
static const char red_yellow[]= "#a82a00";     // Rojo amarillento (antes amarillo)
static const char pink[]      = "#ff003c";     // Rosa rojizo
static const char col_borderbar[] = "#0e0e0e"; // Negro (borde interior)
