[colors.cursor]
cursor = "0xffffff"
text = "0x000000"

[colors.primary]
background = "0x000000"  # Fondo negro
foreground = "0xe0e0e0"  # Texto gris claro

[font]
size = 23.0

[font.normal]
family = "xos4 Terminus"
style = "Regular"

[terminal.shell]
program = "/bin/zsh"

[window]
decorations = "none"
dynamic_padding = true
opacity = 0.85  # Transparencia más sutil

[window.padding]
x = 8
y = 8

[cursor]
style = "Beam"
[terminal]



